apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: airwave-rbac-su-cluster-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows the user "dar" to read pods in the "airwave-rbac" namespace.
kind: ClusterRoleBinding
metadata:
  name: airwave-rbac-su-clusterrole-binding
subjects:
# - kind: User # An example of binding a User to a Role
#   name: dar # Name is case sensitive
#   apiGroup: rbac.authorization.k8s.io
- kind: Group # A group (O in the CSR)
  name: superusers # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: airwave-rbac-su-cluster-role # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

